apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaffold-server-gateway
  labels:
    app: scaffold-server-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaffold-server-gateway
  template:
    metadata:
      labels:
        app: scaffold-server-gateway
    spec:
      containers:
        - name: scaffold-server-gateway
          image: registry.cn-shenzhen.aliyuncs.com/thymizhang/scaffold-server-gateway:1.0.0
          imagePullPolicy: Always #每次都重新拉取镜像
          env:
            - name: aliyun_logs_scaffold-server-gateway-stdout #阿里云日志服务采集配置，创建一个名为scaffold-server-gateway-stdout的logstore
              value: stdout  #将stdout作为采集路径
            - name: SPRING_PROFILES_ACTIVE #多环境配置参数
              value: test
          livenessProbe: #存活探针
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30 #等待30秒开始检查
            periodSeconds: 60 #每60秒检查一次
          resources:
            requests: #请求资源下限
              cpu: "100m"
              memory: "128Mi"
            limits:  #资源上限, 大于等于requests
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: server-gateway
  labels:
    app: server-gateway
    group: scaffold
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: lb-wz9haqtf9f9ecs0u7zx9a  #绑定已有的SLB(负载均衡服务)
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: 'true' #强制覆盖SLB之前的监听
spec:
  ports:
    - name: http
      port: 9000
      targetPort: 9000  #pod的端口, 可以不填, 默认就是port的值
  selector:
    app: scaffold-server-gateway #路由规则: 匹配pod中的labels标签
  type: LoadBalancer