apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaffold-server-security
  labels:
    app: scaffold-server-security
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scaffold-server-security
  template:
    metadata:
      labels:
        app: scaffold-server-security
    spec:
      containers:
        - name: scaffold-server-security
          image: registry.cn-shenzhen.aliyuncs.com/thymizhang/scaffold-server-security:1.0.0
          imagePullPolicy: Always #每次都重新拉取镜像
          env:
            - name: aliyun_logs_scaffold-server-security-stdout #阿里云日志服务采集配置，创建一个名为scaffold-server-security-stdout的logstore
              value: stdout  #将stdout作为采集路径
            - name: SPRING_PROFILES_ACTIVE #多环境配置参数
              value: test
          readinessProbe: #就绪探针
            httpGet:
              path: /login #需要依赖spring-boot-starter-actuator
              port: 8080 #k8s内部端口
            initialDelaySeconds: 10 #等待10秒开始检查
          livenessProbe: #存活探针
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30 #等待30秒开始检查
            periodSeconds: 60 #每60秒检查一次
          resources:
            requests: #请求资源下限
              cpu: "100m"
              memory: "128Mi"
            limits:  #资源上限, 大于等于requests
              memory: "512Mi"
---
#如果使用k8s的服务发现机制，需要配置下面的service
#apiVersion: v1
#kind: Service
#metadata:
#  name: server-security
#  labels:
#    app: server-security
#    group: scaffold
#spec:
#  ports:
#    - name: http
#      port: 8080
#      targetPort: 8080  #pod的端口, 可以不填, 默认就是port的值
#      nodePort: 31080 #对k8s集群暴露的端口
#  selector:
#    app: scaffold-server-security #路由规则: 匹配pod中的labels标签
#  type: NodePort