server:
  port: ${port:8080}

---

spring:
  application:
    name: server-security
  main:
    allow-bean-definition-overriding: true

---

spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.gceasy.cc:8848
        namespace: SCAFFOLD-DEV

---

spring:
  redis:
    database: 0
    host: redis.gceasy.cc
    port: 6379 #默认6379，可省略
    timeout: 30000  # 连接超时时长（毫秒）
    lettuce:
      pool: # 注意: 使用连接池需要加入commons-pool2依赖
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10    # 连接池中的最大空闲连接
        min-idle: 5     # 连接池中的最小空闲连接
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）

---

springfox:
  documentation:
    swagger-ui:
      enabled: false # 关闭swagger在线文档