apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaffold-service-company
  labels:
    app: scaffold-service-company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaffold-service-company
  template:
    metadata:
      labels:
        app: scaffold-service-company
    spec:
      containers:
        - name: scaffold-service-company
          image: registry.cn-hangzhou.aliyuncs.com/thymizhang/scaffold-service-company:1.0.0
          imagePullPolicy: IfNotPresent
          readinessProbe: #就绪探针
            httpGet:
              path: /actuator/health #需要依赖spring-boot-starter-actuator
              port: 8083 #k8s内部端口
            initialDelaySeconds: 10 #等待10秒开始检查
          livenessProbe: #存活探针
            tcpSocket:
              port: 8083
            initialDelaySeconds: 30 #等待30秒开始检查
            periodSeconds: 60 #每60秒检查一次
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: service-company
#  labels:
#    app: service-company
#    group: scaffold
#spec:
#  ports:
#    - name: http
#      port: 8083
#      targetPort: 8083  #pod的端口, 可以不填, 默认就是port的值
#      nodePort: 31083 #对k8s集群暴露的端口
#  selector:
#    app: scaffold-service-company #路由规则: 匹配pod中的labels标签
#  type: NodePort